/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/
package com.testdefaultprefabs.bubbledata.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testdefaultprefabs.bubbledata.Bubble;

/**
 * Service object for domain model class {@link Bubble}.
 */
public interface BubbleService {

    /**
     * Creates a new Bubble. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Bubble if any.
     *
     * @param bubble Details of the Bubble to be created; value cannot be null.
     * @return The newly created Bubble.
     */
	Bubble create(@Valid Bubble bubble);


	/**
	 * Returns Bubble by given id if exists.
	 *
	 * @param bubbleId The id of the Bubble to get; value cannot be null.
	 * @return Bubble associated with the given bubbleId.
     * @throws EntityNotFoundException If no Bubble is found.
	 */
	Bubble getById(Integer bubbleId) throws EntityNotFoundException;

    /**
	 * Find and return the Bubble by given id if exists, returns null otherwise.
	 *
	 * @param bubbleId The id of the Bubble to get; value cannot be null.
	 * @return Bubble associated with the given bubbleId.
	 */
	Bubble findById(Integer bubbleId);


	/**
	 * Updates the details of an existing Bubble. It replaces all fields of the existing Bubble with the given bubble.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on Bubble if any.
     *
	 * @param bubble The details of the Bubble to be updated; value cannot be null.
	 * @return The updated Bubble.
	 * @throws EntityNotFoundException if no Bubble is found with given input.
	 */
	Bubble update(@Valid Bubble bubble) throws EntityNotFoundException;

    /**
	 * Deletes an existing Bubble with the given id.
	 *
	 * @param bubbleId The id of the Bubble to be deleted; value cannot be null.
	 * @return The deleted Bubble.
	 * @throws EntityNotFoundException if no Bubble found with the given id.
	 */
	Bubble delete(Integer bubbleId) throws EntityNotFoundException;

	/**
	 * Find all Bubbles matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Bubbles.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<Bubble> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all Bubbles matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Bubbles.
     *
     * @see Pageable
     * @see Page
	 */
    Page<Bubble> findAll(String query, Pageable pageable);

    /**
	 * Exports all Bubbles matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Bubbles in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the Bubble.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

